vscode:
  extensions:
    - Vue.volargitpod.io/docs/introduction/learn-gitpod/gitpod-yaml)
    - bradlc.vscode-tailwindcss# and commit this file to your remote git repository to share the goodness with others.
    - rvest.vs-code-prettier-eslint# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
    - WakaTime.vscode-wakatime  
    


tasks:
  - init: npm install && npm run build
    command: npm run dev
