vscode:
  extensions:
    - Vue.volargitpod.io/docs/introduction/learn-gitpod/gitpod-yaml)
    - bradlc.vscode-tailwindcss# and commit this file to your remote git repository to share the goodness with others.
    - rvest.vs-code-prettier-eslint    
tasks:
  - init: npm install && npm run build
    command: npm run dev
